name: CI/CD Pipeline

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

  test:
    needs: build

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  deploy:
    needs: test

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Deploy to staging environment
      run: npm run deploy

  # Add a failure notification step
  notify_failure:
    needs: [build, test, deploy]
    runs-on: ubuntu-latest

    steps:
    - name: Notify on failure
      if: ${{ failure() }}
      uses: actions/github-script@v6
      with:
        script: |
          const failureMessage = `❌ Workflow failed on ${github.repository}!`;
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: failureMessage,
            body: failureMessage,
            labels: ['notification']
          });
 
